// INGREDIENT ACTION TYPES
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT";
export const FETCH_INGREDIENT = "FETCH_INGREDIENT";

// CATEGORY ACTION TYPES
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
